# 머신러닝
### 지도학습
    - 분류
    - 회귀
    - 추천시스템
    - 시각 / 음성감지 / 인지
    - 텍스트분석 / NLP
### 비지도학습
    - 클러스트링
    - 차원 축소
    - 강화학습

## 파이썬 머신러닝 패키지
 - 사이킷런(Scikit-Learn) : 머신러닝
 - 텐서플로, 케라스 : 딥러닝
 - 넘파이(Numpy) : 행렬, 선형대수
 - 사이파이(Scipy) : 자연과학, 통계
 - 판다스(pandas) : 2차원 데이터 처리
 - Matplotlib, Seaborn : 시각화

## Numpy
- Numerical Python
- 선형대수 기반, 대량 데이터의 배열 연산 가능
- ndarray 데이터 타입 => N-dimension array
    - ndarray내의 데이터에는 숫자 / 문자열 / 불 값 모두 가능
    - 하지만 같은 데이터 타입만 가능

### ndarray 
- array() : 다양한 인자를 입력받아 ndarray로 변환
- ndarray.shape : ndarray의 차원과 크기를 tuple 로 나타냄
- ndim : 차원 확인
- dtype : ndarray 내의 데이터 타입 확인


In [10]:
array1 = np.array([1,2,3])
print('array1 type :',type(array1))
print('array1 array 형태 :',array1.shape) # 1차원 array로 3개 데이터 가짐

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태 :', array2.shape) # 2차원 array로 2개 로우, 3개 칼럼

array3 = np.array([[1,2,3]])
print('array3 type :',type(array3))
print('array3 array 형태 :', array3.shape,'\n')

print('array1 : {:0}차원, array2 : {:1}차원, array3 : {:2}차원'.format(array1.ndim, array2.ndim,
                                                                array3.ndim))
      

array1 type : <class 'numpy.ndarray'>
array1 array 형태 : (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태 : (2, 3)
array3 type : <class 'numpy.ndarray'>
array3 array 형태 : (1, 3) 

array1 : 1차원, array2 : 2차원, array3 :  2차원


In [11]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


==============================================================

- 리스트는 다른 데이터 타입가능
- ndarray 내엔 같은 데이터 타입만 가능
- 만약 데이터 유형이 섞여있는 리스트를 ndarray 변경시엔 더 큰 데이터 타입으로 형변환
- astype() : ndarray내 데이터 타입 변경



In [2]:
# int형과 string형 => string으로 변환
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

# int형과 float형 => float형
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

# astype()
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64
[1. 2. 3.] float64


### ndarray 생성
- arange() : array를 range로 표현 (0 ~ N-1)
- zeros() : 튜플 형태로 shape값 입력, dtype값 정해주지 않으면 float64형이 기본
- ones() : 튜플 형태로 shape값 입력, dtype값 정해주지 않으면 float64형이 기본

In [9]:
array1 = np.arange(10)
print(array1)
print(array1.dtype, array1.shape,'\n')

array2 = np.zeros((3,2),dtype = 'int32')
print(array2)
print(array2.dtype, array2.shape,'\n')

array3 = np.ones((3,2))
print(array3)
print(array3.dtype, array3.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,) 

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2) 

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


- reshape()
    - ndarray의 차원과 크기 변경
    - 지정된 사이즈로 변경 불가능하면 오류 발생
    - 인자로 -1 사용 => 원래 ndarray 와 호환되는 새로운 shape로 변경
    - reshape(-1,1) 같은 형태로 자주 사용 => 형태 통일 위해 (2차원)
- tolist() : ndarray를 리스트 자료형으로 변환

In [11]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print(array2, array2.shape)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)


In [17]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print(array3d)
print(array3d.tolist(),'\n')

array2 = array3d.reshape(-1,1)
print(array2)
print(array2.shape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0, 1], [2, 3]], [[4, 5], [6, 7]]] 

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(8, 1)


### ndarray 데이터 선택
- 1. 특정한 데이터만 추출 : 인덱스 값 지정
- 2. 슬라이싱 : ':'기호 사용. (시작인덱스) ~ (종료인덱스-1)의 ndarray 반환
- 3. 팬시 인덱싱 : 연속된 인덱스 값 말고 끊어서 보고 싶을때 사용. 일정한 인덱싱 집합을 리스트 / ndarray 형태로 지정
- 4. 불린 인덱싱 : 특정 조건에 해당하는 위치의 ndarray 반환

=  1번빼곤 모두 ndarray 추출 

##### axis = 0 : row 방향, =1 : column 방향

In [22]:
# 단일값 선택
array1 = np.arange(1,10)
print('array1:',array1)
value = array1[2]
print(value, type(value))
print('맨 뒤의 값:',array1[-1],'\n')

array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)
print(array2d[0,0],array2d[0,1],array2d[2,2])

array1: [1 2 3 4 5 6 7 8 9]
3 <class 'numpy.int32'>
맨 뒤의 값: 9 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1 2 9


In [28]:
# 슬라이싱

array1 = np.arange(1,10)
array3 = array1[0:3]
print(array3, type(array3))
print(array1[:3])
print(array1[3:])
print(array1[:],'\n')

array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)
print('array2d[0:2,0:2]\n',array2d[0:2,0:2])
print('array2d[1:3,:]\n',array2d[1:3,:])
print('array2d[:2,0]\n',array2d[:2,0],'\n')

print(array2d[0]) # 2차원 ndarray에서 뒤에오는 인덱스 없애면 1차원 반환, 3 => 2
print(array2d[0].shape)

[1 2 3] <class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9] 

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:2,0]
 [1 4] 

[1 2 3]
(3,)


In [31]:
# 팬시 인덱싱
array1d=  np.arange(1,10)
array2d = array1d.reshape(3,3)

array3 = r=array2d[[0,1],2]
print(array3.tolist())

array4 = array2d[[0,1],0:2]
print(array4.tolist())

array5 = array2d[[0,1]]
print(array5.tolist())

[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]


In [35]:
# 불린 인덱싱 => [] 안에 조건문 지정

array1d = np.arange(1,10)
array3 = array1d[array1d > 5]
print(array1d > 5)
print(array3,'\n')

indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print(array4)

# 1. 필터링 조건을 []안에 기재
# 2. True값에 해당하는 인덱스값만 저장
# 3. 저장된 인덱스 데이터 세트로 ndarray조회

[False False False False False  True  True  True  True]
[6 7 8 9] 

[6 7 8 9]


### 행렬정렬
- np.sort() : 원행렬 유지한채 정렬된 행렬 반환
- ndarray.sort() : 원행렬 자체를 정렬한채로 변환. 반환값은 None
- argsort() : 정렬된 행렬의 인덱스를 ndarray형태로 반환

=> 기본적으로 오름차순. 내림차순 정렬시 [::-1]

=> 행렬 2차원 이상시 axis 축값 설정해 정렬 수행

In [42]:
array1 = np.array([3,1,9,5])
print('원본행렬:',array1,'\n')

sort_array1 = np.sort(array1)
print('반환된 행렬:',sort_array1)
print('원본행렬 :',array1)

sort_array2 = array1.sort()
print('반환된 행렬:',sort_array2)
print('원본행렬 :',array1)

sort_array1_desc = np.sort(array1)[::-1]
print('내림차순으로 정렬:',sort_array1_desc,'\n')

# 2차원 이상
array2d = np.array([[8,12],
                   [7,1]])
print(array2d)
print('로우 방향으로 정렬:\n',np.sort(array2d,axis=0))
print('칼럼 방향으로 정렬:\n',np.sort(array2d,axis=1))


원본행렬: [3 1 9 5] 

반환된 행렬: [1 3 5 9]
원본행렬 : [3 1 9 5]
반환된 행렬: None
원본행렬 : [1 3 5 9]
내림차순으로 정렬: [9 5 3 1] 

[[ 8 12]
 [ 7  1]]
로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [4]:
# 정렬된 행렬의 인덱스 반환
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬시 원본 행렬의 인덱스 :',sort_indices)

sort_indices_desc = np.argsort(org_array)[::-1]
print(type(sort_indices_desc))
print('행렬 내림차순 정렬시 원본 행렬의 인덱스 :',sort_indices_desc)

#  ndarray는 테이블이나 df처럼 메타데이터 가질수 없음
# 즉 np.argsort()을 이용해 반환된 인덱스를 name_array에 팬시 인덱스로 적용

name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬시 score_array 인덱스 :',sort_indices_asc)
print('성적 오름차순 정렬시 name_array 이름 출력 :',name_array[sort_indices_asc])

<class 'numpy.ndarray'>
행렬 정렬시 원본 행렬의 인덱스 : [1 0 3 2]
<class 'numpy.ndarray'>
행렬 내림차순 정렬시 원본 행렬의 인덱스 : [2 3 0 1]
성적 오름차순 정렬시 score_array 인덱스 : [0 2 4 1 3]
성적 오름차순 정렬시 name_array 이름 출력 : ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산
- 행렬 내적 : np.dot()
- 전치 행렬 : np.transpose() => 행과 열 위치 교환

In [6]:
# 행렬 내적
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])
dot_product = np.dot(A,B)
print(dot_product,'\n')

# 전치 행렬
A = np.array([[1,2],
             [3,4]])
transpose_mat = np.transpose(A)
print(transpose_mat)

[[ 58  64]
 [139 154]] 

[[1 3]
 [2 4]]
